# Generated by Django 2.2.12 on 2020-07-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20, unique=True)),
                ('designation', models.CharField(default='', max_length=10)),
                ('year', models.CharField(default='2020', max_length=4)),
                ('branch', models.CharField(default='', max_length=10)),
                ('dob', models.DateField()),
                ('qualification', models.TextField(default='', max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('experience', models.TextField()),
                ('specialization', models.TextField()),
                ('subjects', models.TextField()),
            ],
        ),
    ]
