# Generated by Django 2.2.12 on 2020-07-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year_book', '0002_studentevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevents',
            name='achievements',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
