# Generated by Django 2.2.12 on 2020-07-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='usertype',
            new_name='utype',
        ),
    ]
