# Generated by Django 2.2.12 on 2020-07-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200706_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enroll_id',
            field=models.TextField(default='', max_length=15),
        ),
    ]
